openapi: "3.0.3"
info:
  title: ponto-eletronico-api
  version: 0.0.1
  description: Este serviço simula um sistema de ponto eletronico

servers:
  - url: http://localhost:8080/swagger-ui.html#
    description: Caso o projeto esteja rodando localmente você conseguirá consultar este swagger no endereço acima.

paths:
  /api/cadastrar-pf:
    post:
      summary: cadastrar uma pessoa física
      requestBody:
        description: informações para cadastro da pessoa física
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '201':
          description: mensagem 201 created
          content:
            application/json:
              schema:
                type: object
                example:
                  message: created

  /debug-sentry:
    post:
      summary: Send an error to Sentry

      requestBody:
        description: Optional error text to send to Sentry.
        required: false
        content:
          application/json:
            schema:
              type: object
            example:
              errorMessage: My first Sentry Error

      responses:
        '200':
          description: Confirmation that the error was sent.
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Error sent to Sentry: "My first error"'

  /debug-rollbar:
    post:
      summary: Send an error to Rollbar

      requestBody:
        description: Optional error text to send to Rollbar.
        required: false
        content:
          application/json:
            schema:
              type: object
            example:
              errorMessage: My first Rollbar Error

      responses:
        '200':
          description: Confirmation that the error was sent.
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Error sent to Rollbar: "My first error"'