apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ponto-eletronico-api
  description: Este serviço simula um sistema de ponto eletronico
  links:
    - url: https://github.com/thi2pra1/ponto-eletronico-api
      title: GitHub Repositorio
      icon: github
  tags:
    - java
    - backend
  annotations:
    github.com/project-slug: thi2pra1/ponto-eletronico-api
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: team-a

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  title: swagger-ponto-eletronico-api
  name: swagger-ponto-eletronico-api
  description: Este serviço simula um sistema de ponto eletronico
  tags:
    - stable
spec:
  type: openapi
  lifecycle: production
  owner: team-a
  system: sample-system
  definition:
    $text: https://github.com/thi2pra1/ponto-eletronico-api/blob/master/api-spec.yaml