apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ponto-eletronico-api
  description: Este serviço simula um sistema de ponto eletronico
  links:
    -url: https://github.com/swagger-ui.html#/
     title: Swagger
     icon: github
  tags:
    - java
    - backend
spec:
  type: service
  lifecycle: production
  owner: team-a