apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ponto-eletronico-api
  description: Este serviço simula um sistema de ponto eletronico
  links:
    - url: https://github.com/thi2pra1/ponto-eletronico-api
      title: GitHub Repositorio
      icon: github
  tags:
    - java
    - backend
  annotations:
    github.com/project-slug: value
spec:
  type: service
  lifecycle: production
  owner: team-a